# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

r:
  - release

env:
  - PACKAGE_VERSION="0.5.0"

os:
  - linux
  - osx

before_install:
  - Rscript -e 'utils::update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
